fariintiland/accounts/urls.py
from django.conf.urls import url
from django.urls import path, include

from .import views

app_name = 'accounts'

urlpatterns = [
    url('signup/', views.signup_view, name="signup" ),
    url('login/', views.login_view, name="login"),
    url('logout/', views.logout_view, name="logout"),
]

fariintiland/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('jurnal/', views.jurnal, name='jurnal'),
    path('berita/', views.berita, name='berita'),
    path('<int:angka>/', views.angka),
    path('category/<str:category>/', views.category, name='category'),
    path('post/<slug:slug>/', views.singlePost, name='singlepost'),

    path('', views.index, name= 'index'),
]

fariintiland/fariintiland/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "home"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name= 'index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
    path('inputdata/', include('input_data.urls', namespace='inputdata')),
    path('forecasting/', include('forecasting.urls', namespace='forecasting')),
    path('komparasi/', include('komparasi.urls', namespace='komparasi')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]
 

fariintiland/input_data/urls.py
from django.urls import path

from . import views

app_name = "input_data"

urlpatterns = [
    path('', views.index , name='index'),
    path('input/', views.create , name='input'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('update/<int:update_id>', views.update, name='update'),
        path('inputcsv/', views.inputcsv , name='inputcsv'),


]

fariintiland/komparasi/urls.py
from django.urls import path, include
from .views import index, hasilKomparasi, hasilKomparasiTahun, indextahun, hasilKomparasiItem, hasilKomparasiTahunIndex

app_name = "komparasi"

urlpatterns = [
    path('', index , name='index'),
    path('indextahun/', indextahun , name='indextahun'),

    path('hasilkomparasi/', hasilKomparasi, name ='hasilkomparasi' ),
    path('hasilkomparasiitem/', hasilKomparasiItem, name ='hasilkomparasiitem' ),

    path('hasilkomparasitahun/', hasilKomparasiTahun, name ='hasilkomparasitahun' ),
    path('hasilkomparasitahunitem/', hasilKomparasiTahunIndex, name ='hasilkomparasitahunitem' ),


]

fariintiland/templates/snippets/navbar.html
{% load static %}


<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
	<br>
</nav>

fariintiland/templates/snippets/scripts.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>

fariintiland/templates/snippets/sidebar-menu.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-left">
      
    <a class="navbar-brand bg-dark navbar-dark" href="{% url "index"%}">Dashboard</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            
                <li class="nav-item">
                    <a class="nav-link" href="{% url "input_data:index"%}">Laporan Penjualan</a>
                </li>
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Peramalan</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item"   href="{% url "forecasting:index"%}">Peramalan Bulanan</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item"  href="{% url "forecasting:indextahun"%}">Peramalan Tahunan</a>
                        </div>
                    </li>
  
                <!-- <li class="nav-item">
                    <a class="nav-link"  href="{% url "komparasi:index"%}">Komparasi Hasil Penjualan</a>
                </li> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Komparasi</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item"  href="{% url "komparasi:index"%}">Komparasi Berdasarkan Bulan</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"  href="{% url "komparasi:indextahun"%}">Komparasi Berdasarkan Tahun</a>
                    </div>
                </li>
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url "about:index"%}">About</a>
                </li>
                <li class="nav-item"> -->
                    <!-- <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form> -->
                    <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>

                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
            {% endif %}
            <!-- <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin</a>
            </li>
             -->
        </ul>
   
    </div>
</nav>

fariintiland/templates/snippets/styles.html
	{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/bootstrap.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/navbar-fixed-left.min.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/docs.css" %}">