fariintiland/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('jurnal/', views.jurnal, name='jurnal'),
    path('berita/', views.berita, name='berita'),
    path('<int:angka>/', views.angka),
    path('category/<str:category>/', views.category, name='category'),
    path('post/<slug:slug>/', views.singlePost, name='singlepost'),

    path('', views.index, name= 'index'),
]

fariintiland/fariintiland/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "home"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name= 'index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
    path('inputdata/', include('input_data.urls', namespace='inputdata')),
    path('forecasting/', include('forecasting.urls', namespace='forecasting')),
    path('komparasi/', include('komparasi.urls', namespace='komparasi')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]
 

fariintiland/input_data/urls.py
from django.urls import path

from . import views

app_name = "input_data"

urlpatterns = [
    path('', views.index , name='index'),
    path('input/', views.create , name='input'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('update/<int:update_id>', views.update, name='update'),
        path('inputcsv/', views.inputcsv , name='inputcsv'),


]

fariintiland/input_data/models.py
from django.db import models

# Create your models here.
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator

def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)  

def validate_even(value):
    try:
        int(value)
        return True
    except ValueError:
        return False

class PenjualanModel(models.Model):
    
    MONTH_CHOICES = (
    ('januari','Januari'),
    ('februari', 'Februari'),
    ('maret','Maret'),
    ('april','April'),
    ('mei','Mei'),
    ('juni', 'Juni'),
    ('juli', 'Juli'),
    ('agustus', 'Agustus'),
    ('september', 'September'),
    ('oktober', 'Oktober'),
    ('november', 'November'),
    ('desember', 'Desember')
    )
    id_penjualan                    = models.AutoField(primary_key = True)
    bulan_transaksi                 =  models.CharField(max_length= 200, choices=MONTH_CHOICES, default='Januari')
    tahun_transaksi                 = models.PositiveIntegerField(
        default=current_year(), validators=[MinValueValidator(2009), max_value_current_year])
    jumlah_hotel                    = models.IntegerField(   null = False, default= 0, validators=[validate_even])
    jumlah_mall                     = models.IntegerField(   null = False, default= 0, validators=[validate_even])
    jumlah_apartemen                = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C441                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C442                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C443                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C451                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C452                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C453                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C461                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C462                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_C463                     = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jasa_pembersih_air              = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jasa_pembersih_kerak_sillica    = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jasa_pembersih_cooling_tower    = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jasa_pembersih_stp              = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_asam_sulfat              = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_molases                  = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_hcl                      = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    jumlah_abf                      = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    pendapatan                      = models.IntegerField(   null= False, default= 0, validators=[validate_even])
    create_time                     = models.DateTimeField(auto_now_add=True)
    update_time                     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}. {}".format(self.tahun_transaksi,  self.id_penjualan)
    

fariintiland/input_data/views.py
from django.shortcuts import render, redirect
import csv, io
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
# Create your views here.
from . import forms
from . import models
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required

@login_required(login_url="/accounts/login/")
def index(request):
    post = models.PenjualanModel.objects.all()
    contact_form = forms.ContactForm()
    # for posts in post:
    #     print(posts.bulan_transaksi)
    context = {
        'heading':'Contact',
        'data_form':contact_form,
        'posts' : post,

    }

    return render(request, 'inputdata/index.html',context)

@login_required(login_url="/accounts/login/")
def create(request):
    contact_form = forms.ContactForm(request.POST or None)
    if request.method == 'POST':
        if models.PenjualanModel.objects.filter(bulan_transaksi = request.POST.get('bulan_transaksi'), tahun_transaksi =request.POST.get('tahun_transaksi')):
            print("masuk")
            return redirect('input_data:index')
        else:

            if contact_form.is_valid():
                contact_form.save()


            return redirect('input_data:index')
        # models.PenjualanModel.objects.create(
        #     bulan_transaksi = request.POST['tanggal_field_month'],
        #     tahun_transaksi = request.POST['tanggal_field_year'],
        #     jumlah_hotel = request.POST['hotel_field'],
        #     jumlah_mall = request.POST['mall_field'],
        #     jumlah_apartemen= request.POST['apartement_field'],
        #     jumlah_C441= request.POST['c441_field'],
        #     jumlah_C442= request.POST['c442_field'],
        #     jumlah_C443= request.POST['c443_field'],
        #     jumlah_C451= request.POST['c451_field'],
        #     jumlah_C452= request.POST['c452_field'],
        #     jumlah_C453= request.POST['c453_field'],
        #     jumlah_C461= request.POST['c461_field'],
        #     jumlah_C462= request.POST['c462_field'],
        #     jumlah_C463= request.POST['c463_field'],
        #     jasa_pembersih_air= request.POST['pembersih_air_field'],
        #     jasa_pembersih_kerak_sillica = request.POST['pembersih_kerak_field'],
        #     jasa_pembersih_cooling_tower = request.POST['pembesih_cooling_tower_field'],
        #     jasa_pembersih_stp = request.POST['pembersih_stp_field'],
        #     jumlah_asam_sulfat =  request.POST['asam_sulfat_field'],
        #     jumlah_molases = request.POST['molases_field'],
        #     jumlah_hcl = request.POST['hcl_field'],
        #     jumlah_abf = request.POST['abf_field'],
        # )
    context = {
        'heading':'Contact',
        'contact_form':contact_form,

    }

    return render(request, 'inputdata/input.html',context)

def delete(request, delete_id):
    models.PenjualanModel.objects.filter(id_penjualan=delete_id).delete()
    return redirect('input_data:index')

def update(request, update_id):
    penjualan = models.PenjualanModel.objects.get(id_penjualan=update_id)

    penjualan_form = forms.ContactForm(request.POST or None, instance=penjualan)
    
    context = {
        'heading':'Update',
        'contact_form':penjualan_form,

    }
    if request.method == 'POST':
        if penjualan_form.is_valid():

           penjualan_form.save()

        return redirect('input_data:index')
    return render(request, 'inputdata/input.html', context)

# @permission_required('admin.can_add_log_entry')
@login_required(login_url="/accounts/login/")
def inputcsv(request):
  
    prompt = {
        'order': 'Urutan data pada CSV yaitu id_penjualan, bulan_transaksi, tahun_transaksi, jumlah_hotel, jumlah_mall, jumlah_apartemen, jumlah_c441, jumlahc442, jumlah_c443, jumlah_c451, jumlahc452, jumlahc453, jumlahc461, jumlahc462, jumlahc463, jasa_pembersih_air, jasa_pembersih_kerak_silica, jasa_pembersih_cooling_tower, jasa_pembersih_stp, jumlah_asam_sulfat, jumlah_molases, jumlah_hcl, jumlah_abf, pendapatan',
        'order2': 'Contoh Penggunaan Pada Excel, gunakan format save .CSV(Comma delimited)'
    }
    
    if request.method == "GET":
         return render(request, 'inputdata/inputcsv.html', prompt)
    csv_file = request.FILES['file']

    if not csv_file.name.endswith('.csv'):
        messages.error(request, "Bukan Format .csv")
    else:
        data_set = csv_file.read().decode('UTF-8')
        io_string = io.StringIO(data_set)
        next(io_string)
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            #  if models.PenjualanModel.objects.filter(id_penjualan=column[0]):
            #     continue
            #  else:
            # for tesst in len(column):
            #     if column[tesst] == None:
           
            try:
                if models.PenjualanModel.objects.filter(bulan_transaksi = column[1], tahun_transaksi = column[2]):
                   
                    models.PenjualanModel.objects.filter(bulan_transaksi = column[1], tahun_transaksi = column[2]).update( bulan_transaksi = column[1],
                    tahun_transaksi = column[2],
                    jumlah_hotel = column[3],
                    jumlah_mall = column[4],
                    jumlah_apartemen= column[5],
                    jumlah_C441= column[6],
                    jumlah_C442= column[7],
                    jumlah_C443= column[8],
                    jumlah_C451= column[9],
                    jumlah_C452= column[10],
                    jumlah_C453= column[11],
                    jumlah_C461= column[12],
                    jumlah_C462= column[13],
                    jumlah_C463= column[14],
                    jasa_pembersih_air= column[15],
                    jasa_pembersih_kerak_sillica = column[16],
                    jasa_pembersih_cooling_tower = column[17],
                    jasa_pembersih_stp = column[18],
                    jumlah_asam_sulfat =  column[19],
                    jumlah_molases = column[20],
                    jumlah_hcl = column[21],
                    jumlah_abf = column[22],
                    pendapatan = column[23] )
                    messages.success(request, "Pada bulan "+ column[1] + " tahun "+ column[2]+" data berhasil di update")
                else:
                    try:   
                        _, created = models.PenjualanModel.objects.update_or_create(
                        bulan_transaksi = column[1],
                        tahun_transaksi = column[2],
                        jumlah_hotel = column[3],
                        jumlah_mall = column[4],
                        jumlah_apartemen= column[5],
                        jumlah_C441= column[6],
                        jumlah_C442= column[7],
                        jumlah_C443= column[8],
                        jumlah_C451= column[9],
                        jumlah_C452= column[10],
                        jumlah_C453= column[11],
                        jumlah_C461= column[12],
                        jumlah_C462= column[13],
                        jumlah_C463= column[14],
                        jasa_pembersih_air= column[15],
                        jasa_pembersih_kerak_sillica = column[16],
                        jasa_pembersih_cooling_tower = column[17],
                        jasa_pembersih_stp = column[18],
                        jumlah_asam_sulfat =  column[19],
                        jumlah_molases = column[20],
                        jumlah_hcl = column[21],
                        jumlah_abf = column[22],   
                        pendapatan = column[23] 
                    )
                        messages.success(request, "Pada bulan "+ column[1] + " tahun "+ column[2]+" data berhasil di masukkan ke database")
                    except IntegrityError:
                        models.PenjualanModel.objects.filter(id_penjualan = column[0]).update( bulan_transaksi = column[1],
                        tahun_transaksi = column[2],
                        jumlah_hotel = column[3],
                        jumlah_mall = column[4],
                        jumlah_apartemen= column[5],
                        jumlah_C441= column[6],
                        jumlah_C442= column[7],
                        jumlah_C443= column[8],
                        jumlah_C451= column[9],
                        jumlah_C452= column[10],
                        jumlah_C453= column[11],
                        jumlah_C461= column[12],
                        jumlah_C462= column[13],
                        jumlah_C463= column[14],
                        jasa_pembersih_air= column[15],
                        jasa_pembersih_kerak_sillica = column[16],
                        jasa_pembersih_cooling_tower = column[17],
                        jasa_pembersih_stp = column[18],
                        jumlah_asam_sulfat =  column[19],
                        jumlah_molases = column[20],
                        jumlah_hcl = column[21],
                        jumlah_abf = column[22],
                        pendapatan = column[23] )
                        messages.success(request, "Pada bulan "+ column[1] + " tahun "+ column[2]+" data berhasil di update")
                    except ValueError:

                        messages.error(request, "Terdapat data kosong di bulan  "+ column[1] + " tahun "+ column[2]+" . Data tidak dimasukkan ke database")
                        break
                
            except ValueError:
                messages.error(request, "Terdapat data kosong di bulan  "+ column[1] + " tahun "+ column[2]+" . Data tidak dimasukkan ke database")
                break
            

    context = {

    }
    return render(request, 'inputdata/inputcsv.html',context)

fariintiland/input_data/templates/inputdata/index.html
{% extends 'base.html' %}
{% load static %}
{% block app_css %}
<link rel="stylesheet" type="text/css"
		href="{% static 'input_data/css/styles.css' %}"> 
{% endblock app_css %}

{% block contents %}
{% if request.user.is_staff %}

<div class = 'row'>
<!-- <a class="nav-link" >Input Data</a></button> -->

<a href="{% url "input_data:input"%}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Input Data</a>



<a href="{% url "input_data:inputcsv"%}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Input Data CSV</a>

<div class="table-wrapper-scroll-y my-custom-scrollbar">

<table class="table table-striped table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Id Penjualan</th>
        <th scope="col">Bulan Transaksi</th>
        <th scope="col">Tahun Transaksi</th>
        <th scope="col">Jumlah Client Hotel</th>
        <th scope="col">Jumlah Client Mall</th>
        <th scope="col">Jumlah Client Apartement</th>
        <th scope="col">Jumlah C441</th>
        <th scope="col">Jumlah C442</th>
        <th scope="col">Jumlah C443</th>
        <th scope="col">Jumlah C451</th>
        <th scope="col">Jumlah C452</th>
        <th scope="col">Jumlah C453</th>
        <th scope="col">Jumlah C461</th>
        <th scope="col">Jumlah C462</th>
        <th scope="col">Jumlah C463</th>
        <th scope="col">Jasa Pembersih Air</th>
        <th scope="col">Jasa Pembersih Kerak Sillica</th>
        <th scope="col">Jasa Pembersih Cooling Tower</th>
        <th scope="col">Jasa Pembersih STP</th>
        <th scope="col">Jumlah Asam Sulfat</th>
        <th scope="col">Jumlah Molases</th>
        <th scope="col">Jumlah HCL</th>
        <th scope="col">Jumlah ABF</th>
        <th scope="col">Pendapatan</th>
        <th scope="col">Update</th>
        <th scope="col">Delete</th>

    </tr>
    </thead>

    <tbody>
    {% for post in posts %}
    <tr> 
        <td>{{forloop.counter}}</td>
        <td>{{ post.id_penjualan }}</td>
        <td>{{ post.bulan_transaksi }}</td>
        <td>{{ post.tahun_transaksi }}</td>
        <td>{{ post.jumlah_hotel }}</td>
        <td>{{ post.jumlah_mall }}</td>
        <td>{{ post.jumlah_apartemen }}</td>
        <td>{{ post.jumlah_C441 }}</td>
        <td>{{ post.jumlah_C442 }}</td>
        <td>{{ post.jumlah_C443 }}</td>
        <td>{{ post.jumlah_C451 }}</td>
        <td>{{ post.jumlah_C452 }}</td>
        <td>{{ post.jumlah_C453 }}</td>
        <td>{{ post.jumlah_C461 }}</td>
        <td>{{ post.jumlah_C462 }}</td>
        <td>{{ post.jumlah_C463 }}</td>
        <td>{{ post.jasa_pembersih_air }}</td>
        <td>{{ post.jasa_pembersih_kerak_sillica}}</td>
        <td>{{ post.jasa_pembersih_cooling_tower}}</td>
        <td>{{ post.jasa_pembersih_stp}}</td>
        <td>{{ post.jumlah_asam_sulfat}}</td>
        <td>{{ post.jumlah_molases}}</td>
        <td>{{ post.jumlah_hcl}}</td>
        <td>{{ post.jumlah_abf}}</td>
        <td>Rp. {{ post.pendapatan}}</td>
        <td>  <a class="btn btn-warning btn-sm" href="{% url 'input_data:update' post.id_penjualan %}" title="">Edit</a></td>
        <td><a class="btn btn-danger btn-sm" href="{% url 'input_data:delete' post.id_penjualan %}" title="">Delete</a></td> 

        </tr>
    {% endfor %}
    </tbody>
</table>
</div>
</div>

{% else %}
        <div class='row'>

                <div class='col-sm-1'></div>
                <div class='col-sm-10'>        
                        <h4 style='margin-left: 36px;'>Hanya User Yang Telah Terkonfirmasi Yang Dapat Mengakses Halaman Ini</h4>
                        </div>

        </div>
        <br>
        <br>
        <div class='row'>

                        <div class='col-sm-2'></div>
                        <div class='col-sm-10'>        
                        <h4 style='margin-left: 20px; color: red;'>Hubungi Administrator Untuk Mengkonfirmasi Akun Anda</h4>
                        </div>
                        
                </div>
                <br>
                <br>
                <div class='row'>

                                <div class='col-sm-5'></div>
                                <div class='col-sm-7'>        
                                <a href="{% url "index"%}" style='margin-left: 20px; font-size:26px'>Kembali</a>
                                </div>
                                
                        </div>
        {% endif %}
{% endblock contents %}

   

		

fariintiland/input_data/templates/inputdata/input.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block contents %}
{% if request.user.is_staff %}

<form method="POST">
    {% csrf_token %}
   

   
            {{contact_form|crispy}}
    
    
        
        <button type="Submit" class="btn btn-primary">Submit</button>
        <a href="{% url "inputdata:index" %}" role="button" class="btn btn-info">Kembali</a>

</form>
<br>
        <h5 style="color:red">Tanda * wajib di isi, nilai 0 adalah angka default untuk mencegah kosongnya form</h5>
        {% else %}
        <div class='row'>

                <div class='col-sm-1'></div>
                <div class='col-sm-10'>        
                        <h4 style='margin-left: 36px;'>Hanya User Yang Telah Terkonfirmasi Yang Dapat Mengakses Halaman Ini</h4>
                        </div>

        </div>
        <br>
        <br>
        <div class='row'>

                        <div class='col-sm-2'></div>
                        <div class='col-sm-10'>        
                        <h4 style='margin-left: 20px; color: red;'>Hubungi Administrator Untuk Mengkonfirmasi Akun Anda</h4>
                        </div>
                        
                </div>
                <br>
                <br>
                <div class='row'>

                                <div class='col-sm-5'></div>
                                <div class='col-sm-7'>        
                                <a href="{% url "index"%}" style='margin-left: 20px; font-size:26px'>Kembali</a>
                                </div>
                                
                        </div>
        {% endif %}

        {% endblock contents %}

   

		 <!-- <div class="form-group">
        {{data_form.tanggal_field.label_tag}}
        {{data_form.bulan_transaksi}}
       
    </div>

    <div class="form-group">
            {{data_form.hotel_field.label_tag}}
            {{data_form.hotel_field}}         
    </div>

    <div class="form-group">
            {{data_form.mall_field.label_tag}}
            {{data_form.mall_field}}         
    </div>

    <div class="form-group">
            {{data_form.apartement_field.label_tag}}
            {{data_form.apartement_field}}         
    </div>

    <div class="form-group">
            {{data_form.c441_field.label_tag}}
            {{data_form.c441_field}}         
    </div>

    <div class="form-group">
            {{data_form.c442_field.label_tag}}
            {{data_form.c442_field}}         
    </div>

    
    <div class="form-group">
            {{data_form.c443_field.label_tag}}
            {{data_form.c443_field }}         
    </div>

    <div class="form-group">
            {{data_form.c451_field.label_tag}}
            {{data_form.c451_field}}         
    </div>

    <div class="form-group">
            {{data_form.c452_field.label_tag}}
            {{data_form.c452_field}}         
    </div>

    <div class="form-group">
            {{data_form.c453_field.label_tag}}
            {{data_form.c453_field}}         
    </div>

    <div class="form-group">
            {{data_form.c461_field.label_tag}}
            {{data_form.c461_field}}         
    </div>

    <div class="form-group">
            {{data_form.c462_field.label_tag}}
            {{data_form.c462_field}}         
    </div>

    <div class="form-group">
            {{data_form.c463_field.label_tag}}
            {{data_form.c463_field}}         
    </div>

    <div class="form-group">
            {{data_form.pembersih_air_field.label_tag}}
            {{data_form.pembersih_air_field}}         
    </div>
    <div class="form-group">
            {{data_form.pembersih_kerak_field.label_tag}}
            {{data_form.pembersih_kerak_field}}         
    </div>

    <div class="form-group">
            {{data_form.pembesih_cooling_tower_field.label_tag}}
            {{data_form.pembesih_cooling_tower_field}}         
    </div>

    <div class="form-group">
            {{data_form.pembersih_stp_field.label_tag}}
            {{data_form.pembersih_stp_field}}         
    </div>

    <div class="form-group">
        {{data_form.asam_sulfat_field.label_tag}}
        {{data_form.asam_sulfat_field}}         
    </div>

    <div class="form-group">
        {{data_form.molases_field.label_tag}}
        {{data_form.molases_field}}         
    </div>

    <div class="form-group">
        {{data_form.hcl_field.label_tag}}
        {{data_form.hcl_field}}         
    </div>

    <div class="form-group">
        {{data_form.abf_field.label_tag}}
        {{data_form.abf_field}}         
    </div> -->

fariintiland/input_data/templates/inputdata/inputcsv.html
{% extends 'base.html' %}
{% load static %}




{% block contents %}
{% if request.user.is_staff %}

    <!-- {% if messages %}
        {% for message in messages %}
            <div>
                <strong>{{message|safe}}</strong>
            </div>
        {% endfor %}
    
    {% endif %} -->
    {% if messages %}
    <div class='row'>
        <div class='col-sm-6 col-sm-offset-3'>
        {% for message in messages %}
            <p {% if message.tags == "success" %} class="alert alert-success" {% else %} class="alert alert-danger" {% endif %}>{{ message }}</p>

            {% endfor %}
    </div>
    </div>
    {% else %}
    <p class="alert alert-info">{{order}}</p>
    <img src="/static/input_data/img/formatcsv.png" class="img-fluid" alt="Responsive image">
    <p class="alert alert-warning">{{order2}}</p>
    {% endif %}
    <br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Upload a file </label>
        <input type="file" name="file">
        <p style="color: red">Hanya Menerima File Berformat .CSV</p>
        <button type="Submit" class="btn btn-primary">Upload</button>
        <a href="{% url "inputdata:index" %}" role="button" class="btn btn-info">Kembali</a>
    </form>
    <br>
    <p class="alert alert-danger">Untuk membuat format .csv bisa menggunakan Excel atau Text Editor seperti notepad++, atom dan visual studio code</p>
    {% else %}
    <div class='row'>

            <div class='col-sm-1'></div>
            <div class='col-sm-10'>        
                    <h4 style='margin-left: 36px;'>Hanya User Yang Telah Terkonfirmasi Yang Dapat Mengakses Halaman Ini</h4>
                    </div>

    </div>
    <br>
    <br>
    <div class='row'>

                    <div class='col-sm-2'></div>
                    <div class='col-sm-10'>        
                    <h4 style='margin-left: 20px; color: red;'>Hubungi Administrator Untuk Mengkonfirmasi Akun Anda</h4>
                    </div>
                    
            </div>
            <br>
            <br>
            <div class='row'>

                            <div class='col-sm-5'></div>
                            <div class='col-sm-7'>        
                            <a href="{% url "index"%}" style='margin-left: 20px; font-size:26px'>Kembali</a>
                            </div>
                            
                    </div>
    {% endif %}
{% endblock contents %}