fariintiland/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('jurnal/', views.jurnal, name='jurnal'),
    path('berita/', views.berita, name='berita'),
    path('<int:angka>/', views.angka),
    path('category/<str:category>/', views.category, name='category'),
    path('post/<slug:slug>/', views.singlePost, name='singlepost'),

    path('', views.index, name= 'index'),
]

fariintiland/fariintiland/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "home"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name= 'index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
    path('inputdata/', include('input_data.urls', namespace='inputdata')),
    path('forecasting/', include('forecasting.urls', namespace='forecasting')),
    path('komparasi/', include('komparasi.urls', namespace='komparasi')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

]
 

fariintiland/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    category = models.CharField(max_length=255, default="berita")
    slug = models.SlugField(blank=True, editable=False)
    waktu_posting = models.DateTimeField(auto_now_add=True)
    waktu_update= models.DateTimeField(auto_now=True)
    def save(self):
        self.slug = slugify(self.title)
        super(Post, self).save()
    def __str__(self):
        return "{}. {}".format(self.id, self.title)

fariintiland/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Post
# Create your views here.

def index(request):

    posts = Post.objects.all() 
    categories = Post.objects.values('category').distinct()

    context = {
        'title' : 'Blog',
        'heading': 'Blog',
        'posts' : posts,
        'categories': categories,
        'content' : 'Ini adalah blog',
        'subheading': 'Jurnal Kelas Terbuka',
        'kontributor' : 'yudha',
        'banner' : 'blog/img/banner_blog.png',
        'app_css' : 'blog/css/styles.css',
        'nav': [
            ['/', 'Home'],
            ['/blog', 'Blog'],
            ['/about', 'About'],
        ]
    }
    return render(request, 'blog/index.html', context)

def berita(request):

    posts = Post.objects.filter(category__iexact='berita')
    context = {
        'title' : 'Blog',
        'heading': 'Blog',
        'posts' : posts,
        'subheading': 'Jurnal Kelas Terbuka',
        'kontributor' : 'yudha',
        'banner' : 'blog/img/banner_blog.png',
        'app_css' : 'blog/css/styles.css',
        'nav': [
            ['/', 'Home'],
            ['/blog', 'Blog'],
            ['/about', 'About'],
        ]
    }
    return render(request, 'blog/index.html', context)

def jurnal(request):

    posts = Post.objects.filter(category__iexact='jurnal')
    context = {
        'title' : 'Blog',
        'heading': 'Blog',
        'posts' : posts,
        'subheading': 'Jurnal Kelas Terbuka',
        'kontributor' : 'yudha',
        'banner' : 'blog/img/banner_blog.png',
        'app_css' : 'blog/css/styles.css',
        'nav': [
            ['/', 'Home'],
            ['/blog', 'Blog'],
            ['/about', 'About'],
        ]
    }
    return render(request, 'blog/index.html', context)

def angka(request, angka):

    posts = Post.objects.filter(id__iexact=angka)
    context = {
        'title' : 'Blog',
        'heading': 'Blog',
        'posts' : posts,
        'subheading': 'Jurnal Kelas Terbuka',
        'kontributor' : 'yudha',
        'banner' : 'blog/img/banner_blog.png',
        'app_css' : 'blog/css/styles.css',
        'nav': [
            ['/', 'Home'],
            ['/blog', 'Blog'],
            ['/about', 'About'],
        ]
    }
    return render(request, 'blog/index.html', context)


def category(request, category):

    posts = Post.objects.filter(category=category)
    categories = Post.objects.values('category').distinct()
    context = {
        'title' : 'Category',
        'heading': 'Category',
        'content' : 'tampilkan berdasarkan category',
        'posts' : posts,
        'subheading': 'Jurnal Kelas Terbuka',
        'kontributor' : 'yudha',
        'categories' : categories,
        'banner' : 'blog/img/banner_blog.png',
        'app_css' : 'blog/css/styles.css',
        'nav': [
            ['/', 'Home'],
            ['/blog', 'Blog'],
            ['/about', 'About'],
        ]
    }
    return render(request, 'blog/category.html', context)

def singlePost(request, slug):

    posts = Post.objects.get(slug=slug)
    categories = Post.objects.values('category').distinct()
    context = {
        'title' : 'Blog',
        'heading': 'Blog',
        'posts' : posts,
        'categories': categories,
        'subheading': 'Jurnal Kelas Terbuka',
        'kontributor' : 'yudha',
        'banner' : 'blog/img/banner_blog.png',
        'app_css' : 'blog/css/styles.css',
        'nav': [
            ['/', 'Home'],
            ['/blog', 'Blog'],
            ['/about', 'About'],
        ]
    }
    return render(request,'blog/detail.html', context)

fariintiland/blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}
{% block app_css %}
<link rel="stylesheet" type="text/css"
		href="{% static "blog/css/styles.css"%}"> 
{% endblock app_css %}

{% block header %}
<h1 class="text-left" style="margin-top:200px">{{heading}}</h1>
<p class="lead text-left">{{subheading}}</p>
{% endblock header %}

{% block contents %}
    {{content}}

  
<ul class= "nav">

            <li class="nav-item">
                <a class="nav-link" href ="/blog" title="">All-post</a>
            </li>   
    {% for dataCategory in categories %}
        
            <li class="nav-item">
                <a class="nav-link" href ="{% url "blog:category" dataCategory.category %}" title="">{{dataCategory.category}}</a>
            </li>
        
    {% endfor %}
</ul>

    {% for post in posts %}
        <a href = "/blog/post/{{post.slug}}" title="">
            <h1>{{post.title}}</h1>
        </a>
            <p>{{post.waktu_posting}}</p>
            <p>{{post.body|truncatechars:200}}</p>

    {% endfor %}

{% endblock contents %}

fariintiland/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}
{% block app_css %}
<link rel="stylesheet" type="text/css"
		href="{% static "blog/css/styles.css"%}"> 
{% endblock app_css %}

{% block header %}
<h1 class="text-left" style="margin-top:200px">{{heading}}</h1>
<p class="lead text-left">{{subheading}}</p>
{% endblock header %}

{% block contents %}
    {{content}}
<ul class= "nav">

            <li class="nav-item">
                <a class="nav-link" href ="/blog" title="">All-post</a>
            </li>   
    {% for dataCategory in categories %}
        
            <li class="nav-item">
                <a class="nav-link" href ="{% url "blog:category" dataCategory.category %}" title="">{{dataCategory.category}}</a>
            </li>
        
    {% endfor %}
</ul>
    <h1>{{posts.title}}</h1>
    <p>{{posts.waktu_posting}}</p>
    <p>{{posts.body}}</p>

{% endblock contents %}

fariintiland/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>{{title}}</title>
</head>
<body>
    <h1>{{title}}</h1>
    <h2>{{heading}}</h2>

    {% for post in posts %}
        <h3>{{post.title}}</h3>
        <h3>{{post.waktu_posting}}</h3>
        <p>{{post.body}}</p> 
        <p>{{post.category}}</p>
        <br>
    {% endfor %}
</body>
</html>